spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-boot-paging-sorting
    username: admin
    password: Passw0rd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

